# -*- coding: utf-8 -*-
"""Conv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16s1jgmmcDRc2nw1pA9ohOjSQeWMDCR3m
"""

import pandas as pd
def generate_nlu_file(filename, excel_file,seprator):
    df = pd.read_excel(excel_file)

    with open(filename, 'w', encoding='utf-8') as file:
        file.write('version: "3.1"\n\nnlu:')
        for index, row in df.iterrows():
            examples = '\n    - '.join(row[7:22].astype(str))
            file.write(f'\n- intent: faq{seprator}{index+1}\n  examples: |\n    - {examples}\n')

def generate_domain_file(filename, excel_file, intent_name, num_examples,seprator):
    df = pd.read_excel(excel_file)
    with open(filename, 'w') as file:
        file.write('version: "3.1"\n\nintents:\n')
        for i in range(num_examples):
            file.write(f'  - {intent_name}{seprator}{i+1}\n')

        file.write('\nresponses:\n')

        for index, row in df.iterrows():
            file.write(f'  utter_{intent_name}{seprator}{index+1}:\n')
            file.write(f'  - text: "{row[1]}"\n\n')

        file.write('session_config:\n  session_expiration_time: 60\n  carry_over_slots_to_new_session: true\n')
def generate_rules_file(filename, num_rules):
    with open(filename, 'w') as file:
        file.write('version: "3.1"\n\nrules:\n\n')

        for i in range(num_rules):
            file.write(f'- rule: faq {i+1}\n')
            file.write(f'  steps:\n')
            file.write(f'  - intent: faq_{i+1}\n')
            file.write(f'  - action: utter_faq_{i+1}\n\n')

generate_nlu_file('nlu.yml', 'MCI_Internet_TrainData.xlsx',"_")
generate_nlu_file('test_nlu.yml', 'MCI_Internet_TestData.xlsx',"_")
generate_domain_file('domain.yml', 'MCI_Internet_TrainData.xlsx', 'faq', 50,"_")
generate_rules_file('rules.yml', 50)

"""# 2"""

generate_nlu_file('nlu.yml', 'MCI_Internet_TrainData.xlsx',"/")
generate_nlu_file('test_nlu.yml', 'MCI_Internet_TestData.xlsx',"/")
generate_domain_file('domain.yml', 'MCI_Internet_TrainData.xlsx', 'faq', 50,"/")
generate_rules_file('rules.yml', 50)